---
- hosts: all
  sudo: True
  tasks:

  - name: configure hosts file
    template: src="hosts.j2" dest=/etc/hosts

  - copy: content="DOCKER_NETWORK_OPTIONS=--log-driver=journald" dest=/etc/sysconfig/docker-network
  - name: Make sure docker is running
    service: >
      name=docker
      state=restarted
      enabled=true

  - name: create mesos directory
    file: >
      path=/var/data/mesos
      owner=root
      group=root
      mode=0755
      state=directory
    tags:
      - mounts

  - name: clean up stale mounts
    command: umount -f /sysroot/tmp/mesos
    ignore_errors: yes
    tags:
      - mounts

  - name: Bind-mount mesos sandbox
    mount: >
      opts=bind
      fstype=none
      state=mounted
      name=/sysroot/tmp/mesos
      src=/var/data/mesos
    tags:
      - mounts
      - slave-container

  # Docker issue 18528
  - name: create zookeeper directory
    file: >
      path=/var/data/zk
      owner=root
      group=root
      mode=0755
      state=directory
    tags:
      - issue-18528

  # Docker issue 18528
  - name: create consul directory
    file: >
      path=/var/data/consul
      owner=root
      group=root
      mode=0755
      state=directory
    tags:
      - issue-18528

  - name: zookeeper container
    docker:
      name: zookeeper
      image: "mesoscloud/zookeeper:{{zookeeper_version}}"
      state: present
      net: host
      volumes:
      - "/var/data/zk:/tmp/zookeeper:Z"
      env:
        MYID: "1"
        SERVERS: "{{ipaddr}}"
      ports:
      - "2181:2181"
    tags:
      - zookeeper-container

  - name: master container
    docker:
      name: "mesos-master"
      image: "registry.nutmeg.co.uk:8443/mesos:{{mesos_version}}"
      state: present
      net: host
      command: /usr/sbin/mesos-master
      env:
        MESOS_AUTHENTICATE_SLAVES: true
        MESOS_HOSTNAME: "{{ ipaddr }}"
        MESOS_IP: "{{ ipaddr }}"
        MESOS_QUORUM: 1
        MESOS_ZK: "zk://{{ipaddr}}:2181/mesos"
        MESOS_PORT: 5050
        MESOS_CLUSTER: "local"
        MESOS_LOGGING_LEVEL: WARNING
        SECRET: "{{ mesos_secret }}"
        LIBPROCESS_IP: "{{ ipaddr }}"
      ports:
      - "5050:5050"
    tags:
      - master-container

  - name: marathon container
    docker:
      name: marathon
      image: mesosphere/marathon:{{marathon_version}}
      state: present
      net: host
      env:
        MARATHON_HOSTNAME: "{{ipaddr}}"
        MARATHON_HTTPS_ADDRESS: "{{ipaddr}}"
        MARATHON_HTTP_ADDRESS: "{{ipaddr}}"
        MARATHON_MASTER: "zk://{{ipaddr}}:2181/mesos"
        MARATHON_ZK: "zk://{{ipaddr}}:2181/marathon"
        MARATHON_TASK_LAUNCH_TIMEOUT: 1500000
        MARATHON_EVENT_SUBSCRIBER: http_callback
        SECRET: "{{ mesos_secret }}"
        LIBPROCESS_IP: "{{ ipaddr }}"
    tags:
      - marathon-container

  - name: consul container
    docker:
      name: consul
      image: progrium/consul
      state: present
      net: host
      privileged: true
      command: -server -bootstrap-expect 1 -advertise "{{ipaddr}}" -recursor 8.8.8.8 -node "{{node_name}}"
      volumes:
      - "/var/data/consul:/data:Z"
    tags:
      - consul-container

  - name: install service files
    template: src="service.j2" dest="/etc/systemd/system/{{item}}.service"
    with_items:
    - mesos-master
    - zookeeper
    - marathon
    - consul

  - name: start services
    service: name={{item}} state=started enabled=yes
    with_items:
    - mesos-master
    - zookeeper
    - marathon
    - consul